name: vocabvault2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.3+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  google_ml_kit: ^0.19.0
  google_mlkit_text_recognition: ^0.14.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_mobile_ads: ^5.3.1
  firebase_storage: ^12.4.4
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  translator: ^1.0.3+1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  confetti: ^0.8.0
  audioplayers: ^6.4.0
  shared_preferences: ^2.2.0
  http: ^1.1.0
  google_sign_in: ^7.0.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

